### ISSUE TITLE
Could not find a healthy node to handle the request.

### ISSUE THREAD

**Issue by pragermh** [biodiversitydata-se/sbdi-support#21]
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/12529363/199683867-0fad162f-fbdd-4f9e-b1e4-e9dfba8a655f.png">

**Comment by Inkimar** [comment]
**Workflow to the error**
1. https://tools.biodiversitydata.se/
2. menu -> search & explore -> search records
3. https://records.biodiversitydata.se/#tab_simpleSearch 
4. press the 'search'-button
5. ERROR -> see Marias screenshot above

**Comment by Inkimar** [comment]
logs , solr -> 


```
beta_solr1.1.78feph223y4e@solr-1    | java.lang.OutOfMemoryError: Java heap space
beta_solr1.1.78feph223y4e@solr-1    | 2022-11-03 12:02:29.217 ERROR (qtp1409092880-2314) [c:biocache s:shard1 r:core_node3 x:biocache_shard1_replica_n1] o.a.s.s.HttpSolrCall null:java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
beta_solr1.1.78feph223y4e@solr-1    | 	at org.apache.solr.servlet.HttpSolrCall.sendError(HttpSolrCall.java:664)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:531)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:395)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:341)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.Server.handle(Server.java:502)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
beta_solr1.1.78feph223y4e@solr-1    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
beta_solr1.1.78feph223y4e@solr-1    | 	at java.base/java.lang.Thread.run(Thread.java:834)
beta_solr1.1.78feph223y4e@solr-1    | Caused by: java.lang.OutOfMemoryError: Java heap space
beta_solr1.1.78feph223y4e@solr-1    | 
beta_solr1.1.78feph223y4e@solr-1    | 2022-11-03 12:02:29.244 WARN  (qtp1409092880-2314) [c:biocache s:shard1 r:core_node3 x:biocache_shard1_replica_n1] o.e.j.s.HttpChannel /solr/biocache_shard1_replica_n1/select
beta_solr1.1.78feph223y4e@solr-1    | java.lang.OutOfMemoryError: Java heap space

```

**Comment by Inkimar** [comment]
Action :

1. docker service update --force beta_solr1
2.  docker service update --force beta_solr2
3.  docker service update --force beta_solr3
4.  docker service update --force beta_solr4

**Comment by Inkimar** [comment]
Test the workflow: 

1. https://tools.biodiversitydata.se/
2. menu -> search & explore -> search records
3. https://records.biodiversitydata.se/#tab_simpleSearch
4. press the 'search'-button
5. OK -> 103,417,222 results for [all records]    


![image](https://user-images.githubusercontent.com/3329613/199728377-4e8ddf5e-c164-424d-8af4-71143aa0f509.png)

**Comment by pragermh** [comment]
Excellent, thanks!
